Diagnostics:
  UnusedIncludes: None
  MissingIncludes: Strict

---

If:
  Match: [.*\.cpp$]

CompileFlags:
  Remove:
    - -Wunused-variable
    - -Wunused-parameter
    - -Wunused-result
  Add: 
    - -std=c++14
    - -pipe
    - -Wall
    - -Wextra
    - -Wshadow
    - -Wno-unused-variable
    - -Wno-unused-parameter
    - -Wno-unused-result
    - -Wno-unused-but-set-variable
    - -Wfloat-equal
    - -march=native
    - -DLOCAL
    - -O2
    - -I/usr/include
Index:
  Background: Build
  Threads: 0

---

If:
  Match: [.*\.c$]
CompileFlags:
  Add: [-std=c11]