Diagnostics:
  UnusedIncludes: None
  MissingIncludes: Strict
CompileFlags:
  Add: 
    - -std=c++17
    - -Wall
    - -Wextra
    - -Wshadow
    - -Wno-unused-variable
    - -march=native
    - -DLOCAL
    - -O2 # Tối ưu hóa để clangd hiểu các đoạn code phức tạp nhanh hơn
  Remove: [-W*] # Loại bỏ các flag cũ không cần thiết

Index:
  Background: Build # Cho phép lập chỉ mục ở chế độ nền
  Threads: 0